apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Singullaritty/playground-gitops.git
    targetRevision: HEAD
    path: k8s-deployment
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true