apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
 name: github-runner-api
 namespace: actions-runner-system
spec:
 replicas: 2
 template:
   spec:
     labels:
     - k8s-runner
     serviceAccountName: github-runner-api-sa
     automountServiceAccountToken: true
     repository: Singullaritty/playground-gitops 
